#!/usr/bin/env python
# -*- coding: utf-8 -*-


import sys
import json

from layabout import Layabout, MissingToken

app = Layabout()
repri = json.dumps


@app.handle('message')
def print_all(slack, event):
    if event.get('bot_id') is None:
        print(' '.join([
            'Message', repri(event['channel']), repri(event['text'])
        ]))


if __name__ == "__main__":
    try:
        app.run()
    except MissingToken:
        sys.exit('Unable to find Slack API token on LAYABOUT_TOKEN env var.\n')
